//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR_Laboratory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class analyzer_service
    {
        public int id_analuzer_service { get; set; }
        public int id_service { get; set; }
        public int id_analyzer { get; set; }
    
        public virtual analyzer analyzer { get; set; }
        public virtual service service { get; set; }
    }
}
