//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR_Laboratory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class analyzer_blood_service
    {
        public int id_analyzer_blood_service { get; set; }
        public int id_blood_service { get; set; }
        public int id_analyzer { get; set; }
        public System.DateTime date_reception { get; set; }
        public Nullable<System.DateTime> date_finished { get; set; }
        public Nullable<decimal> analyze_time_sec { get; set; }
    
        public virtual analyzer analyzer { get; set; }
        public virtual blood_service blood_service { get; set; }
    }
}
