//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR_Laboratory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class blood
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public blood()
        {
            this.blood_service = new HashSet<blood_service>();
        }
    
        public int id_blood { get; set; }
        public int id_patient { get; set; }
        public decimal barcode { get; set; }
        public System.DateTime date_create { get; set; }
        public decimal analyze_time_days { get; set; }
        public int id_status { get; set; }
    
        public virtual patient patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blood_service> blood_service { get; set; }
        public virtual status status { get; set; }
    }
}
