//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR_Laboratory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int id_history { get; set; }
        public Nullable<int> id_user { get; set; }
        public string login { get; set; }
        public System.DateTime date_time { get; set; }
        public string ip { get; set; }
        public bool has_entered { get; set; }
    
        public virtual user user { get; set; }
    }
}
