//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR_Laboratory.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Laboratory : DbContext
    {
        public Laboratory()
            : base("name=Laboratory")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<analyzer> analyzer { get; set; }
        public virtual DbSet<analyzer_blood_service> analyzer_blood_service { get; set; }
        public virtual DbSet<blood> blood { get; set; }
        public virtual DbSet<blood_service> blood_service { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<employee_service> employee_service { get; set; }
        public virtual DbSet<history> history { get; set; }
        public virtual DbSet<insurance> insurance { get; set; }
        public virtual DbSet<patient> patient { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_type> user_type { get; set; }
    }
}
